### ISSUE TITLE
Use es6 template literal to concatenate strings

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/deaf-grandma-js-problem-Sandeep-raj#1]
https://github.com/sro-boeing-wave-2/deaf-grandma-js-problem-Sandeep-raj/blob/fe528baf7c72315b2e1a77c60882f1d2d3c75e14/index.js#L34

**Comment by Sandeep-raj** [comment]
es6 template is used to concatenate strings with some variables
