### ISSUE TITLE
Remove variables if it's not reused

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/deaf-grandma-js-problem-Sandeep-raj#2]
https://github.com/sro-boeing-wave-2/deaf-grandma-js-problem-Sandeep-raj/blob/fe528baf7c72315b2e1a77c60882f1d2d3c75e14/index.js#L31-L32

**Comment by Sandeep-raj** [comment]
Variables that are not needed are removed.
