### ISSUE TITLE
Scope of the variables not required outside the function, hence can be declared and initialized within the function

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/deaf-grandma-js-problem-Sandeep-raj#3]
https://github.com/sro-boeing-wave-2/deaf-grandma-js-problem-Sandeep-raj/blob/fe528baf7c72315b2e1a77c60882f1d2d3c75e14/index.js#L17-L18

**Comment by Sandeep-raj** [comment]
all the variables that are not required to be global is placed inside the function.
